# Generated by Django 3.0.2 on 2020-02-14 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='engagementStart',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='frequency',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='representative',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
