# Generated by Django 3.0.2 on 2020-02-21 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20200214_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Community')),
            ],
        ),
        migrations.CreateModel(
            name='EventToSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recommendedDate', models.DateField()),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Community')),
            ],
        ),
    ]
