# Generated by Django 3.0.2 on 2020-02-21 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_eventtoschedule_scheduledevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='engagementStop',
            field=models.DateField(default=datetime.datetime(2020, 2, 21, 18, 30, 6, 445484)),
            preserve_default=False,
        ),
    ]
