# Generated by Django 3.0.2 on 2020-02-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_community_engagementstop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='representative',
            name='address',
            field=models.TextField(),
        ),
    ]
