# Generated by Django 3.0.2 on 2020-02-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_auto_20200221_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtoschedule',
            name='canceledBefore',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventtoschedule',
            name='isManualyAdded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventtoschedule',
            name='recommendedReview',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventtoschedule',
            name='recommendedDate',
            field=models.DateTimeField(),
        ),
    ]
