# Generated by Django 3.0.2 on 2020-02-21 23:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_auto_20200221_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtoschedule',
            name='recommendedDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventtoschedule',
            name='recommendedTime',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventtoschedule',
            name='recommendedDate',
            field=models.DateField(),
        ),
    ]
