# Generated by Django 3.0.2 on 2020-02-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_auto_20200221_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtoschedule',
            name='recommendedTime',
            field=models.TimeField(default=None, null=True),
        ),
    ]
