# Generated by Django 3.0.2 on 2020-02-22 02:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_auto_20200221_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledevent',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scheduledevent',
            name='date',
            field=models.DateField(),
        ),
    ]
