# Generated by Django 3.0.2 on 2020-02-22 02:33

import community.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0010_auto_20200222_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledevent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=community.models.ScheduledEvent.fromScheduledToCanceled, to=settings.AUTH_USER_MODEL),
        ),
    ]
