# Generated by Django 3.0.2 on 2020-02-11 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isOfficerManager', models.BooleanField(default=False)),
                ('isDepartmentManager', models.BooleanField(default=False)),
                ('isEventManager', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departments', models.CharField(default='', max_length=100)),
                ('communities', models.CharField(default='', max_length=100)),
                ('badgeNumber', models.CharField(default='', max_length=100)),
                ('roles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Roles')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deparmentName', models.CharField(default='', max_length=100)),
                ('departmentDescription', models.CharField(default='', max_length=255)),
                ('responsibleOfficer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
