# Generated by Django 3.0.2 on 2020-02-11 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='user',
        ),
    ]
