# Generated by Django 3.0.2 on 2020-02-11 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_remove_roles_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='roles',
        ),
        migrations.AddField(
            model_name='department',
            name='roles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Roles'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Department'),
        ),
    ]
