# Generated by Django 3.0.2 on 2020-02-13 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0002_department_iscommunitymanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='communities',
        ),
        migrations.AlterField(
            model_name='department',
            name='departmentDescription',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='department',
            name='departmentName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='badgeNumber',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
