# Generated by Django 3.0.2 on 2020-02-25 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20200213_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.Department'),
        ),
    ]
