# Generated by Django 3.0.2 on 2020-02-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20200211_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='roles',
        ),
        migrations.AddField(
            model_name='department',
            name='isDepartmentManager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='department',
            name='isEventManager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='department',
            name='isOfficerManager',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
